import path from "node:path";
import { fileURLToPath } from "node:url";
import { localeRedirects } from "./lib/i18n/routing.mjs";
import { isNonProductionDeployment, NOINDEX_HEADER, SECURITY_HEADERS } from "./lib/security-headers.mjs";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// BUILD MODE
//
// Production (gogulf.co, deployed from `main`) is still a static export and stays that
// way until the approved cutover. The redesign branch builds in server mode only
// (decision D9): PLATFORM_MODE=server locally and on staging. The static path is kept
// intact for `main` and is removed in the cutover commit. See docs/MIGRATION-PLAN.md.
// ---------------------------------------------------------------------------
const isServerMode = process.env.PLATFORM_MODE === "server";

/** @type {import('next').NextConfig} */
const nextConfig = {
  ...(isServerMode ? {} : { output: "export", images: { unoptimized: true } }),

  poweredByHeader: false,

  // A stray package-lock.json sits in the parent directory, outside this git
  // repository. Pinning the root stops Turbopack treating that as the workspace.
  turbopack: {
    root: projectRoot,
  },

  // The app has several root layouts (English, the other languages in app/[locale],
  // /admin, /portal), so a URL that matches no route is rendered by
  // app/global-not-found.tsx. See docs/I18N.md.
  //
  // experimental.inlineCss was measured on 12 Sep 2026 and NOT adopted. It removed the two
  // render-blocking stylesheets, but the home page's lab LCP moved only ~0.3 s (3.6 → 3.3 s,
  // within Lighthouse's run-to-run noise) while its HTML grew from ~122 KB to ~299 KB
  // uncompressed (the CSS is carried twice: <style> and the RSC payload) and every page lost
  // stylesheet caching. The remaining render delay is framework JavaScript executing before
  // the first paint under a 4x CPU throttle. Revisit only with field data.
  experimental: {
    globalNotFound: true,
  },

  ...(isServerMode
    ? {
        // Every page and asset. /admin and /portal responses generated by proxy.ts
        // carry the same headers (see lib/security-headers.mjs).
        async headers() {
          return [
            {
              source: "/:path*",
              headers: [...SECURITY_HEADERS, ...(isNonProductionDeployment() ? [NOINDEX_HEADER] : [])],
            },
          ];
        },
        // English is canonical without a prefix (/en/jobs → /jobs), and old public asset
        // URLs that other sites and caches may still hold.
        async redirects() {
          return [
            ...localeRedirects(),
            { source: "/assets/go-gulf-logo.png", destination: "/brand/logo-512.png", permanent: true },
            { source: "/assets/logo-circle.png", destination: "/brand/logo-512.png", permanent: true },
            { source: "/assets/og-image.jpg", destination: "/opengraph-image", permanent: true },
            { source: "/icons/icon-192.png", destination: "/brand/logo-192.png", permanent: true },
            { source: "/icons/icon-512.png", destination: "/brand/logo-512.png", permanent: true },
          ];
        },
      }
    : {}),
};

export default nextConfig;
